import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { availability, createBooking, displayDateTime, isBookableDate, now, ownerChatId, scheduleGuestReminder, slotTimes } from "../reservation-domain.js";

registerMainMenuItem({ label: "📅 Book a table", data: "booking:new", order: 10 });
registerMainMenuItem({ label: "My reservation", data: "booking:mine", order: 20 });
const composer = new Composer<Ctx>();
const dates = (): string[] => Array.from({ length: 7 }, (_, i) => new Date(now().getTime() + i * 86_400_000).toISOString().slice(0, 10));
const bookingKeyboard = (date: string) => inlineKeyboard([...dates().map((day) => [inlineButton(day === date ? `✓ ${day}` : day, `book:date:${day}`)]), [inlineButton("⬅️ Back to menu", "menu:main")]]);
function confirmationText(b: { referenceCode: string; partySize: number; datetime: string }): string { return `Your table is confirmed for ${b.datetime.slice(0, 10)} at ${b.datetime.slice(11, 16)} for ${b.partySize}. Your reference is ${b.referenceCode}.`; }
async function notifyOwner(ctx: Ctx, text: string): Promise<void> { const owner = await ownerChatId(ctx); if (owner !== undefined && owner !== ctx.chat!.id) { try { await ctx.api.sendMessage(owner, text); } catch { /* A blocked owner must not undo a booking. */ } } }

composer.callbackQuery("booking:new", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.step = "choosing_date"; await ctx.editMessageText("Choose the day you’d like to visit.", { reply_markup: bookingKeyboard("") }); });
composer.callbackQuery(/^book:date:\d{4}-\d{2}-\d{2}$/, async (ctx) => { await ctx.answerCallbackQuery(); const date = ctx.callbackQuery.data.slice("book:date:".length); if (!isBookableDate(date)) { await ctx.editMessageText("That day has passed. Choose a future date.", { reply_markup: bookingKeyboard("") }); return; } ctx.session.draft = { date }; ctx.session.step = "choosing_date"; const times = slotTimes(date); await ctx.editMessageText(`Here are the times we can welcome you on ${date}. Choose one, then we’ll check the right table for your party.`, { reply_markup: inlineKeyboard([...times.map((time) => [inlineButton(time, `book:time:${time}`)]), [inlineButton("Choose another day", "booking:new")]]) }); });
composer.callbackQuery(/^book:time:\d{2}:00$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!ctx.session.draft?.date) { await ctx.editMessageText("Let’s start with a date.", { reply_markup: bookingKeyboard("") }); return; } ctx.session.draft.time = ctx.callbackQuery.data.slice("book:time:".length); await ctx.editMessageText("How many guests are joining you?", { reply_markup: inlineKeyboard([[1,2,3,4].map((n) => inlineButton(String(n), `book:size:${n}`)), [5,6,7,8].map((n) => inlineButton(String(n), `book:size:${n}`)), [inlineButton("Choose another time", `book:date:${ctx.session.draft.date}`)]]) }); });
composer.callbackQuery(/^book:size:[1-8]$/, async (ctx) => { await ctx.answerCallbackQuery(); const draft = ctx.session.draft; if (!draft?.date || !draft.time) { await ctx.editMessageText("Let’s choose a date and time first.", { reply_markup: bookingKeyboard("") }); return; } const partySize = Number(ctx.callbackQuery.data.slice("book:size:".length)); const slots = await availability(ctx, draft.date, partySize); if (!slots.some((s) => s.time === draft.time)) { await ctx.editMessageText("That time has just been taken for this party size. Choose another available time.", { reply_markup: inlineKeyboard([...slots.map((s) => [inlineButton(`${s.time} · ${s.label}`, `book:time:${s.time}`)]), [inlineButton("Choose another day", "booking:new")]]) }); return; } draft.partySize = partySize; ctx.session.draft = draft; ctx.session.step = "choosing_details"; await ctx.editMessageText(`Your ${draft.time} table for ${partySize} is available. Add your name and phone number, or keep it simple.`, { reply_markup: inlineKeyboard([[inlineButton("Add my details", "book:details")], [inlineButton("Skip", "book:confirm")]]) }); });
composer.callbackQuery("book:details", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.step = "choosing_details"; await ctx.editMessageText("Send your name and phone number in one message, for example: Sam, +44 7700 900000.", { reply_markup: inlineKeyboard([[inlineButton("Skip", "book:confirm")]]) }); });
composer.callbackQuery("book:confirm", async (ctx) => { await ctx.answerCallbackQuery(); const draft = ctx.session.draft; if (!draft?.date || !draft.time || !draft.partySize) { await ctx.editMessageText("Your booking details expired. Let’s choose a new date.", { reply_markup: bookingKeyboard("") }); return; } const booking = await createBooking(ctx, { date: draft.date, time: draft.time, partySize: draft.partySize, name: draft.name, phone: draft.phone }); if (!booking) { await ctx.editMessageText("That table is no longer available. Choose another time and we’ll check again.", { reply_markup: inlineKeyboard([[inlineButton("Choose a new time", `book:date:${draft.date}`)]]) }); return; } await scheduleGuestReminder(ctx, booking); ctx.session.step = "idle"; ctx.session.draft = undefined; await ctx.editMessageText(confirmationText(booking), { reply_markup: inlineKeyboard([[inlineButton("Reschedule", "booking:reschedule"), inlineButton("Cancel", "booking:cancel")], [inlineButton("Back to menu", "menu:main")]]) }); await notifyOwner(ctx, `New reservation: ${displayDateTime(booking)} for ${booking.partySize}.`); });
composer.on("message:text", async (ctx, next) => { if (ctx.session.step !== "choosing_details" || !ctx.session.draft) return next(); const parts = ctx.message.text.split(",").map((part) => part.trim()).filter(Boolean); if (parts.length < 2) { await ctx.reply("Send both your name and phone number, separated by a comma, or tap Skip."); return; } ctx.session.draft = { ...ctx.session.draft, name: parts[0], phone: parts.slice(1).join(", ") }; await ctx.reply("Thanks. Tap Confirm to reserve your table.", { reply_markup: inlineKeyboard([[inlineButton("Confirm booking", "book:confirm")], [inlineButton("Skip details", "book:confirm")]]) }); });
composer.callbackQuery("booking:mine", async (ctx) => { await ctx.answerCallbackQuery(); const { bookingForGuest } = await import("../reservation-domain.js"); const booking = await bookingForGuest(ctx); await ctx.editMessageText(booking ? `Your upcoming table is ${displayDateTime(booking)} for ${booking.partySize}. Reference: ${booking.referenceCode}.` : "You don’t have an upcoming reservation yet — tap Book a table to make one.", { reply_markup: booking ? inlineKeyboard([[inlineButton("Reschedule", "booking:reschedule"), inlineButton("Cancel", "booking:cancel")], [inlineButton("Back to menu", "menu:main")]]) : inlineKeyboard([[inlineButton("Book a table", "booking:new")], [inlineButton("Back to menu", "menu:main")]]) }); });
export default composer;
